using System.Text.Json.Serialization;

namespace MiniPayment.Api.Models;

/// <summary>Payment response payload.</summary>
public sealed class PayResponse
{
    /// <summary>Unique UUID generated by this system.</summary>
    [JsonPropertyName("transaction_id")]
    public Guid TransactionId { get; set; }

    /// <summary>Unique mock reference number returned by the "bank".</summary>
    [JsonPropertyName("acquirer_reference")]
    public string AcquirerReference { get; set; } = null!;

    /// <summary>Two-digit response code (00 = approved, others = declined).</summary>
    [JsonPropertyName("response_code")]
    public string ResponseCode { get; set; } = null!;

    /// <summary>Transaction status: APPROVED, DECLINED, FAILED, or UNKNOWN.</summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = null!;

    /// <summary>Transaction timestamp in ISO 8601 format.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; set; }

    /// <summary>Transaction amount.</summary>
    [JsonPropertyName("amount")]
    public decimal Amount { get; set; }

    /// <summary>Human-readable result message.</summary>
    [JsonPropertyName("message")]
    public string Message { get; set; } = null!;
}
